service: example-go-app-exp

provider:
  name: aws
  runtime: go1.x
  region: eu-west-1
  environment:
    EPSAGON_TOKEN: ${env:EPSAGON_TOKEN}
    EPSAGON_COLLECTOR_URL: ${env:EPSAGON_COLLECTOR_URL}

functions:
  write:
    handler: main
    events:
    - http:
        path: exp
        method: post
