// Code generated by protoc-gen-go. DO NOT EDIT.
// source: trace.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Trace struct {
	AppName              string       `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	Token                string       `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Event                []*Event     `protobuf:"bytes,3,rep,name=event,proto3" json:"event,omitempty"`
	Exception            []*Exception `protobuf:"bytes,4,rep,name=exception,proto3" json:"exception,omitempty"`
	Version              string       `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Platform             string       `protobuf:"bytes,6,opt,name=platform,proto3" json:"platform,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Trace) Reset()         { *m = Trace{} }
func (m *Trace) String() string { return proto.CompactTextString(m) }
func (*Trace) ProtoMessage()    {}
func (*Trace) Descriptor() ([]byte, []int) {
	return fileDescriptor_0571941a1d628a80, []int{0}
}

func (m *Trace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trace.Unmarshal(m, b)
}
func (m *Trace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trace.Marshal(b, m, deterministic)
}
func (m *Trace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trace.Merge(m, src)
}
func (m *Trace) XXX_Size() int {
	return xxx_messageInfo_Trace.Size(m)
}
func (m *Trace) XXX_DiscardUnknown() {
	xxx_messageInfo_Trace.DiscardUnknown(m)
}

var xxx_messageInfo_Trace proto.InternalMessageInfo

func (m *Trace) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

func (m *Trace) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Trace) GetEvent() []*Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *Trace) GetException() []*Exception {
	if m != nil {
		return m.Exception
	}
	return nil
}

func (m *Trace) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Trace) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func init() {
	proto.RegisterType((*Trace)(nil), "protocol.Trace")
}

func init() { proto.RegisterFile("trace.proto", fileDescriptor_0571941a1d628a80) }

var fileDescriptor_0571941a1d628a80 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0xcd, 0xaa, 0xc2, 0x30,
	0x10, 0x85, 0xe9, 0xed, 0x4d, 0x7f, 0xa6, 0x8b, 0x42, 0x74, 0x11, 0xbb, 0x2a, 0x82, 0xd0, 0x55,
	0x41, 0x7d, 0x06, 0xb7, 0x2e, 0x8a, 0x7b, 0x89, 0x65, 0x04, 0xb1, 0x4d, 0x86, 0x18, 0x8a, 0x8f,
	0xe8, 0x63, 0x49, 0x13, 0x5b, 0x5d, 0x85, 0x6f, 0xbe, 0x33, 0x93, 0x03, 0x99, 0x35, 0xb2, 0xc5,
	0x9a, 0x8c, 0xb6, 0x9a, 0x27, 0xee, 0x69, 0x75, 0x57, 0xe4, 0xf8, 0x6c, 0x91, 0xec, 0x4d, 0x2b,
	0xaf, 0x8a, 0x0c, 0x07, 0x54, 0xd6, 0xc3, 0xfa, 0x15, 0x00, 0x3b, 0x8d, 0x7b, 0x7c, 0x05, 0x89,
	0x24, 0x3a, 0x2b, 0xd9, 0xa3, 0x08, 0xca, 0xa0, 0x4a, 0x9b, 0x58, 0x12, 0x1d, 0x65, 0x8f, 0x7c,
	0x09, 0xcc, 0xea, 0x3b, 0x2a, 0xf1, 0xe7, 0xe6, 0x1e, 0xf8, 0x06, 0x98, 0xbb, 0x24, 0xc2, 0x32,
	0xac, 0xb2, 0x5d, 0x5e, 0x4f, 0x5f, 0xd6, 0x87, 0x71, 0xdc, 0x78, 0xcb, 0xb7, 0x90, 0xce, 0x0d,
	0xc4, 0xbf, 0x8b, 0x2e, 0x7e, 0xa2, 0x93, 0x6a, 0xbe, 0x29, 0x2e, 0x20, 0x1e, 0xd0, 0x3c, 0xc6,
	0x05, 0xe6, 0x9b, 0x7c, 0x90, 0x17, 0x90, 0x50, 0x27, 0xed, 0x55, 0x9b, 0x5e, 0x44, 0x4e, 0xcd,
	0x7c, 0x89, 0xdc, 0xd1, 0xfd, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x9a, 0x80, 0x3a, 0xfb, 0x08, 0x01,
	0x00, 0x00,
}
