service: s3-example-go-app

custom:
  BucketName: s3-golang-test-bucket-epsagon

provider:
  name: aws
  runtime: go1.x
  region: eu-west-1
  environment:
    EPSAGON_TOKEN: ${env:EPSAGON_TOKEN}
    EPSAGON_COLLECTOR_URL: ${env:EPSAGON_COLLECTOR_URL}
    BUCKET_NAME: ${self:custom.BucketName}

  iamRoleStatements:
  - Effect: Allow
    Action:
    - s3:*
    Resource: "arn:aws:s3::*:${self:custom.BucketName}/*"
  - Effect: Allow
    Action:
    - s3:*
    Resource: "arn:aws:s3::*:${self:custom.BucketName}"

functions:
  write:
    handler: write/main
    events:
    - http:
        path: write
        method: post
  write_v2:
    handler: write_v2/main
    events:
    - http:
        path: write_v2
        method: post
  trigger:
    handler: trigger/main
    events:
    - s3:
        bucket: ${self:custom.BucketName}
        event: s3:ObjectCreated:*
