service: s3-example-go-app

custom:
  BucketName: s3-example-go

provider:
  name: aws
  runtime: go1.x
  region: eu-west-1
  environment:
    EPSAGON_TOKEN: ${env:EPSAGON_TOKEN}
    EPSAGON_COLLECTOR_URL: ${env:EPSAGON_COLLECTOR_URL}

  iamRoleStatements:
  - Effect: Allow
    Action:
    - s3:*
    Resource: "arn:aws:s3::*:${self:custom.BucketName}"

functions:
  write:
    handler: write/main
    events:
    - http:
        path: write
        method: post
    environment:
      BUCKET_NAME: ${self:custom.BucketName}
  hello:
    handler: trigger/main
    events:
    - s3:
        bucket: s3-example-go
        event: s3:ObjectCreated:*
