// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.1
// source: testapp.proto

package testapp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UnaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UnaryRequest) Reset() {
	*x = UnaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testapp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryRequest) ProtoMessage() {}

func (x *UnaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_testapp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryRequest.ProtoReflect.Descriptor instead.
func (*UnaryRequest) Descriptor() ([]byte, []int) {
	return file_testapp_proto_rawDescGZIP(), []int{0}
}

func (x *UnaryRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UnaryResponse) Reset() {
	*x = UnaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testapp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnaryResponse) ProtoMessage() {}

func (x *UnaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_testapp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnaryResponse.ProtoReflect.Descriptor instead.
func (*UnaryResponse) Descriptor() ([]byte, []int) {
	return file_testapp_proto_rawDescGZIP(), []int{1}
}

func (x *UnaryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_testapp_proto protoreflect.FileDescriptor

var file_testapp_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x74, 0x65, 0x73, 0x74, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x28, 0x0a, 0x0c, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x29, 0x0a, 0x0d, 0x55, 0x6e, 0x61,
	0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x32, 0x78, 0x0a, 0x07, 0x54, 0x65, 0x73, 0x74, 0x41, 0x70, 0x70, 0x12,
	0x31, 0x0a, 0x0e, 0x44, 0x6f, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0d, 0x2e, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0e, 0x2e, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x3a, 0x0a, 0x17, 0x44, 0x6f, 0x55, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x0d, 0x2e,
	0x55, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x55,
	0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x04,
	0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_testapp_proto_rawDescOnce sync.Once
	file_testapp_proto_rawDescData = file_testapp_proto_rawDesc
)

func file_testapp_proto_rawDescGZIP() []byte {
	file_testapp_proto_rawDescOnce.Do(func() {
		file_testapp_proto_rawDescData = protoimpl.X.CompressGZIP(file_testapp_proto_rawDescData)
	})
	return file_testapp_proto_rawDescData
}

var file_testapp_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_testapp_proto_goTypes = []interface{}{
	(*UnaryRequest)(nil),  // 0: UnaryRequest
	(*UnaryResponse)(nil), // 1: UnaryResponse
}
var file_testapp_proto_depIdxs = []int32{
	0, // 0: TestApp.DoUnaryRequest:input_type -> UnaryRequest
	0, // 1: TestApp.DoUnaryRequestWithError:input_type -> UnaryRequest
	1, // 2: TestApp.DoUnaryRequest:output_type -> UnaryResponse
	1, // 3: TestApp.DoUnaryRequestWithError:output_type -> UnaryResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testapp_proto_init() }
func file_testapp_proto_init() {
	if File_testapp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_testapp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testapp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_testapp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_testapp_proto_goTypes,
		DependencyIndexes: file_testapp_proto_depIdxs,
		MessageInfos:      file_testapp_proto_msgTypes,
	}.Build()
	File_testapp_proto = out.File
	file_testapp_proto_rawDesc = nil
	file_testapp_proto_goTypes = nil
	file_testapp_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TestAppClient is the client API for TestApp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TestAppClient interface {
	DoUnaryRequest(ctx context.Context, in *UnaryRequest, opts ...grpc.CallOption) (*UnaryResponse, error)
	DoUnaryRequestWithError(ctx context.Context, in *UnaryRequest, opts ...grpc.CallOption) (*UnaryResponse, error)
}

type testAppClient struct {
	cc grpc.ClientConnInterface
}

func NewTestAppClient(cc grpc.ClientConnInterface) TestAppClient {
	return &testAppClient{cc}
}

func (c *testAppClient) DoUnaryRequest(ctx context.Context, in *UnaryRequest, opts ...grpc.CallOption) (*UnaryResponse, error) {
	out := new(UnaryResponse)
	err := c.cc.Invoke(ctx, "/TestApp/DoUnaryRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testAppClient) DoUnaryRequestWithError(ctx context.Context, in *UnaryRequest, opts ...grpc.CallOption) (*UnaryResponse, error) {
	out := new(UnaryResponse)
	err := c.cc.Invoke(ctx, "/TestApp/DoUnaryRequestWithError", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestAppServer is the server API for TestApp service.
type TestAppServer interface {
	DoUnaryRequest(context.Context, *UnaryRequest) (*UnaryResponse, error)
	DoUnaryRequestWithError(context.Context, *UnaryRequest) (*UnaryResponse, error)
}

// UnimplementedTestAppServer can be embedded to have forward compatible implementations.
type UnimplementedTestAppServer struct {
}

func (*UnimplementedTestAppServer) DoUnaryRequest(context.Context, *UnaryRequest) (*UnaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoUnaryRequest not implemented")
}
func (*UnimplementedTestAppServer) DoUnaryRequestWithError(context.Context, *UnaryRequest) (*UnaryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoUnaryRequestWithError not implemented")
}

func RegisterTestAppServer(s *grpc.Server, srv TestAppServer) {
	s.RegisterService(&_TestApp_serviceDesc, srv)
}

func _TestApp_DoUnaryRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestAppServer).DoUnaryRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TestApp/DoUnaryRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestAppServer).DoUnaryRequest(ctx, req.(*UnaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestApp_DoUnaryRequestWithError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestAppServer).DoUnaryRequestWithError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TestApp/DoUnaryRequestWithError",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestAppServer).DoUnaryRequestWithError(ctx, req.(*UnaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TestApp_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TestApp",
	HandlerType: (*TestAppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoUnaryRequest",
			Handler:    _TestApp_DoUnaryRequest_Handler,
		},
		{
			MethodName: "DoUnaryRequestWithError",
			Handler:    _TestApp_DoUnaryRequestWithError_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "testapp.proto",
}
